single_taipei:
  monthly_costs_ntd:
    rent: 15000
    food: 25000
    transport: 2500
    health_insurance: 5000
    misc: 8333
  placeholders:
    current_capital_ntd: 0        # EDIT ME
    current_age: 35               # EDIT ME
    monthly_work_income_ntd: 40000

single_taichung:
  monthly_costs_ntd:
    rent: 10000
    food: 20000
    transport: 1250
    health_insurance: 5000
    misc: 6667
  placeholders:
    current_capital_ntd: 0        # EDIT ME
    current_age: 35               # EDIT ME
    monthly_work_income_ntd: 40000

couple_taipei:
  monthly_costs_ntd:
    rent: 25000
    food: 50000
    transport: 5000
    health_insurance: 10000
    misc: 15000
  placeholders:
    current_capital_ntd: 0        # EDIT ME
    current_age: 35               # EDIT ME
    monthly_work_income_ntd: 40000

couple_taichung:
  monthly_costs_ntd:
    rent: 18000
    food: 40000
    transport: 2500
    health_insurance: 10000
    misc: 12500
  placeholders:
    current_capital_ntd: 0        # EDIT ME
    current_age: 35               # EDIT ME
    monthly_work_income_ntd: 40000
